# definit la rate limite
# conserve les IPs dans la variable $binary_remote_addr de 10 megabytes
# limite a 10 requetes par secondes
limit_req_zone $binary_remote_addr zone=limite_adresses:10m rate=10r/s;

server {
    listen 80;
    server_name <votre adress ip>;

    # applique la rate limite
    # met jusqu'a 20 requetes dans la file d'attente
    # nodelay fait en sorte que les requetes dans la file d'attente n'aient pas de delais,
    # ce qui evite que l'application apparaisse lante
    limit_req zone=limite_adresses burst=20 nodelay;

    client_max_body_size 20M;

    # 1 - Public site (no auth)
    location / {
        root /var/www/html;
        index index.html;
    }

    # 2 - Protected app
    location /codeproject/ {
        auth_basic "Restricted Access to the Project";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://<votre adress ip>:32168/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}
